name: Build and Deploy Application Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: bankproj      # Your ACR name from the Bicep file
  RESOURCE_GROUP: B-api

jobs:
  build-and-deploy-apps:
    runs-on: ubuntu-latest # Switched back to Ubuntu for speed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Images
        run: |
          az acr login --name ${{ env.ACR_NAME }}
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/account-service:latest ./AccountService
          docker push ${{ env.ACR_NAME }}.azurecr.io/account-service:latest
          
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/transaction-service:latest ./TransactionService
          docker push ${{ env.ACR_NAME }}.azurecr.io/transaction-service:latest
          
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/transaction-worker:latest ./TransactionWorker
          docker push ${{ env.ACR_NAME }}.azurecr.io/transaction-worker:latest

      - name: Update Container Apps with Latest Image
        run: |
          az containerapp update --name account-service --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.ACR_NAME }}.azurecr.io/account-service:latest
          az containerapp update --name transaction-service --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.ACR_NAME }}.azurecr.io/transaction-service:latest
          az containerapp update --name transaction-worker --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.ACR_NAME }}.azurecr.io/transaction-worker:latest